# Generated by Django 4.1.7 on 2023-03-22 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_delivery_time_orderitem_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time of the updating process.')),
                ('status', models.CharField(choices=[('success', 'Executed successfully'), ('fail', 'A critical error occurred'), ('partly_fail', 'There are some errors')], default='success', help_text='Status of process execution.', max_length=11)),
                ('document_timestamp', models.CharField(blank=True, help_text='The information about date and time of document changing.', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateExecutionError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(help_text='Short description of the error.', max_length=100)),
                ('details', models.TextField(blank=True, help_text='Detailed information about the error.')),
                ('update_execution', models.ForeignKey(help_text='The update execution process during execution of which the error occurred.', on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='mainapp.updateexecution')),
            ],
        ),
    ]
